### ISSUE TITLE
Entities walking out of map

### ISSUE THREAD

**Issue by alartum** [alartum/cells#3]
Maybe wrong bounds in DoStep?
MapDump in DoStep shows correct 2x1 field
![image](https://cloud.githubusercontent.com/assets/14263021/25948538/99167050-365c-11e7-9cac-43faa589f42c.png)

For 2x1 field:
![image](https://cloud.githubusercontent.com/assets/14263021/25948622/0321cbfc-365d-11e7-8a59-53d61b0934c2.png)

**Comment by Inkln** [comment]
fixed
